project:
  type: website
  


website:
  title: "CGEs in R - Workshop"
  navbar:
    logo: pics/ofce_m.png
    logo-alt: "OFCE"
    logo-href: "https://www.ofce.fr/"
    right: 
      - href: contact.qmd
        text: Contact
    left:
      - href: index.qmd
        text: Home
      - href: program.qmd
        text: Program
      - href: install.qmd
        text: Get started 
      - href: theory.qmd
        text: Lectures slides
      - href: Exercises_short.qmd
        text: Practical exercices
    tools:
      - icon: github
        href: https://github.com/ThreeME-org/ISIOA_2023_CGEinR-open.git

format:
  ofce-html: default
