---
title: "Practical Sessions supporting materials"
crossref:
        fig-prefix: figure
        tbl-prefix: tableau
        eq-prefix: équation
        sec-prefix: exercise
format: 
  ofce-html:
    number-sections: true
---


<iframe class="slide-deck" src="Practical_Sessions.html" width ="100%" height ="500"></iframe>

:::: panel-tabset

# PS 1: Warm-ups

## Exercise: Installation and tests {#sec-1_1}

-   Follow the installation instructions specified in *Get Started*

-   Run the file `main_test.R` to check if everything is working properly

-   Familiriaze yourself with the folder structure by locating the following files:

    -   `Main.R`
    -   `config_input_MODEL.R` and `config_output.R`
    -   `1_calib_baseline.R`
    -   `01-1-eq_one_equation_model.mdl`

## Exercise: The one equation model {#sec-1_2}

### Part 1

-   Create a copy of the `Main.R` file (call it `Main_one_eq.R` for example) in the root folder

-   On your new `Main` file, call the the config files : `config_input_one_eq.R`, and `config_output_one_eq.R`.

-   Run the simulation and generate the results from templates.

    -   What happens in this shock scenario?
    
### Part 2

-   Look into the data_full database (you can do this in the `Main_one_eq.R` file)

    -   Create a variable rel_diff that computes the relative difference.
    -   Compute a data.frame that contains the GDP (`Y`) growth rate for the baseline and the shock scenario.
    -   Export as a `.csv` files this database

-   Locate where the `.rds` file containing all the simulations results from this project (project name `one_eq`) can be found

-   Create a quarto `qmd` file that :

    -   loads the results from those simulations (project name `one_eq`)
    -   computes the growth rate for the baseline and shock scenarios
    -   makes a graph comparing those two series

-   In the `config_input_one_eq.R`, change the equation `.mdl` file to use `01.2-eq_basic_mod.mdl` file.

    -   Re-run the simulations and the outputs created.
    -   What has changed?



# PS 2: Real models: Walras vs. basic Keynesian

## Exercise: Loading the Walras model {#sec-2_1}

-   Locate the Walras model equation et calibration files

-   Make a copy of the `Main.R`, `config_input_MODEL.R` and `config_output_MODEL.R` files, with a relevant suffix (ie `Main_s.R`)

-   Edit your newly created config_input file:

    -   Change the `project_name` argument to something more relevant
    -   Call the correct `mdl` files
    -   Call upon the correct configuration files in your new main file
    -   Keep the same shock scenario for now

-   Run the simulations with the basic result template.

- Repeat the procedure, this time using the basic Keynes model files. Compare the outputs from the `basic_results` template.

## Exercise: Further results visualization {#sec-2_2}

-   Create your quarto file and create graphs using shortcut plotting functions

    -   `simple_plot()`
    -   `contrib_plot()`

-   Enable the use of the Texdoc template and model_info templates in the `config_output` to generate the equations list for your model.

-   Include the equation index generated by TeXdoc in your newly created `.qmd`

-   Create a table that summarizes the results in relative difference from the baseline for one year after the initial shock, then 2, 3, 10 and 50 for the following variables : GDP, household consumption, public spending and investment. Here's a few steps to help you achieve this:

-   *Identify the year of the shock*

-   *identify the year that correspond to $t+2$, $t+3$, $t+10$ and $t+50$ where $t$ is the year of the initial shock.*

-   *Create a new data.frame from data_full that contains only the relevant variables, compute the relative difference, and keep only the information desired*

-   *reorginize your data.frame to format nicely*

- Use your new `.qmd` to compare simulation results of a shock on public expenditure in a basic Walras model vs a basic Keynesian model by generating two different simulation outputs.



# PS 3: Shocking results

## Exercise: Loading the neokeynesian model {#sec-3_1}

-   Locate the Neokeynesian model `.mdl` files

-   Do the necessary steps (create and modify the relevant files) run the same shock on public spending as we did for the Walras model.

    -   hint: don't forget to change the `project_name` argument

-   Create a similar `.qmd` file as we did for the Walras model. (hint: this can be done very quickly ;) ), complete with the equations lists from TeXdoc.

-   Let's complicate a little bit: on the qmd, place next to eachother the macroeconomic components graphs for each model simulation and same for the table.

## Exercise: New shocks {#sec-3_2}

### Part 1

-   Locate the shock calibration file we have been using so far.

-   Make a copy and call it `2_calib_shock_g_bis.R`

-   Make the necessary changes to the `config_input` file to be able to run this new shock.

-   See if you can reuse the `.qmd` file from @sec-3_1

-   Test the following changes on you new shock calibration file :
      
      - increase in public spending of 5% of GDP
    
- Change your config_input file to simulate both the original shock in public spending and this new one and view both results at once 

### Part 2

- Create new shocks from scratch :
  
    - A sudden (but temporary) decrease in population of -1% in the year 2022
    - A yearly population decrease starting the year 2030 of -0.1% 
    
- Create a new shock calibration file aimed at testing labour productivity shocks (empty for now)

- What is the baseline labour productivity growth in this model ?

- What variable do we have change to create a shock scenario on labour productivity growth and why can't it be `GR_PROG_L`?
  
- Do the necessary (model, results visualization) to answer this question: 
  - **What happens if labour productivity growth increases temporarily to 10% in 2023?**
  - (advanced programmation) : change permanently the labour productivity growth rate starting 2023. (*hint: you might have to use the calibration bubble for this one*)
  


# PS 4: multisectoral model

## Exercise: a multisectoral model

### Part 1

- Using the `01.1_eq_one_eq.mdl` model, add an equation to allow for 2 types of goods to be consumed.
- Check that the simulations run for a `c2_s2` classification, and then a `c4_s4` classification.
- What do you notice in terms of model size?

### Part 2

- Locate the mutlisectoral `.mdl` files. 
- Do the necessary to run simulation on a increase in public expenditure scenario in this scenario








::::
    



